### PR TITLE
Minor update

### PR DESCRIPTION
**Pull request by expressmailing**
Using _PS_JS_DIR_ instead of /js/ in adminmarketingestep3.php
Correction for previous PHP Version in db_marketing.php

### CODE REVIEW

**Comment by gaillafr** [comment]
Thank you @expressmailing, your PR has been merged manually: https://github.com/PrestaShop/expressmailing/commit/94afebcdb48f057559f1dbc9b97c2685bb467030

**Comment by expressmailing** [comment]
Hello @gaillafr 
It seems that the Pull request hasn't been merged with the master branch, it this normal ?

**Comment by gaillafr** [comment]
Yes, that's why I merged it manually.
QA team will have to do some tests before we merge it on the master branch.

**Comment by expressmailing** [comment]
Ok, that's fine.
Thank you @gaillafr

**Comment by expressmailing** [comment]
Hello @gaillafr

Do you know if this update will be applied soon ?
We have some customers on prestashop blocked because of a bug corrected with this update.

Thanks

**Pull request closed without merging**
