### PR TITLE
Update 1.1.7

### PR DESCRIPTION
**Pull request by expressmailing**
- Corrects an issue with the shop url in the default email template. (empty in some cases)
- Updates the configuration of tinymce

### CODE REVIEW

**Comment by expressmailing** [comment]
Hello @Quetzacoalt91 

There is some fixes for a few bugs on our module.
Also we realized that the module wasn't compatible with prestashop < 1.5.6
Is it right to add this in the module ? : 
```php
$this->ps_versions_compliancy = array ('min' => '1.5.6', 'max' => _PS_VERSION_);
```

**Comment by Quetzacoalt91** [comment]
Hi @expressmailing,

I have not checked your PR yet. However about your question, please do not add the property `ps_versions_compliancy` because of a bug on specific version of PrestaShop 1.5. We can add this version restriction on our side in PrestaShop addons.

**Comment by Quetzacoalt91** [comment]
Hi @expressmailing,

Thanks, your PR has just been merged and the changes will be available soon.

Best regards

**Comment by expressmailing** [comment]
Thanks @Quetzacoalt91 

Best regards

**Pull request merged**
